### ISSUE TITLE
*LOVE* the package/idea. Some suggestions and is it possible to donate time/money?

### ISSUE THREAD

**Issue by wsakka** [pipe-dream/laravel#11]
Anders,

Thank you for creating this project. Very excited for it as I can see the power of it and the future potential. I love the smart defaults and behaviours (auto id, timestamps, joins, etc). 

I'm assuming this would be more useful for new projects than additional ones. But it would be great if you can take an already existing schema and import into pipedream so you can build on top of it. I know this is not an easy task but would allow a much larger number of users the ability to use this library.

Secondly, while I agree your naming conventions make sense and your ability to intelligently guess the variable type, it would be great to add very simple syntax so that we can add our expected variable types and other behaviours:

take this schema:

```
Car
name > VARCHAR(100)
brand_id

Driver
fullName > VC(50) - required,min:5 // you can provide/allow for abbreviated column types
yearsOfExperience > Unsigned tinyINT * 
numberOfCollisions > Unsigned tinyInt *
email - email,required 
address !
driver_car
```

I've added for instance above 4 syntactical elements:

- **>** which allows developers to expeclicity set column types
- _*_ which allows developers to indicate this field as fillable
- **-** which allows developers to add validation rules (the rules can be a static class variable)
- **!** add this field to the model's hidden array. 

Obviously there are more possible elements such as these and yes it is possible to individually change them in the JSON but I feel like this would make your already amazing library into something very powerful. The key is to make sure that these optional elements are very easy to use (like the library).

Thank you very much and have a great day.

**Comment by ajthinking** [comment]
Wow, thank you @wsakka! I'm very happy to hear your thoughts about this.

### Question in title
Yes - it's definitly possible to donate time! Money, not at the moment because of my employment status. Thank you for your offer to help. Please check out the Development Roadmap in the readme. What do you think about that?

### New vs Old projects
My first thought was to target the problem of creating new projects. But yes pipe dream could also be used incrementally to modify an existing project.
 
The backend has support for "History", meaning it can rollback previous builds. At each build it saves a JSON file `pipe-dream-history.json`. In that file we could potentially also save the current state of all the fields - so you can close the window and come back later. Or load a JSON from another user.

If you are refering to if it could harvest an arbitary app to recreate a sketch/schema from existing migrations/models files im not sure. That might be a rabbit hole :)

### Attribute property modification directly in sketch
YES! Love it! This is a great idea. I also noted its a pain to scroll through the schema window.

### How to help
Here are some ideas on how to help (for anyone reading this):
* Arcitechture review. Going to Beta as mentioned in the roadmap will require lots of rewriting. Need advice badly, currently Im the only one working on the core code.
* Refactor Vue/Vuex things. I never did that before so its a bit sketchy.
* Tests. There are NO tests right now. I tried pulling in Mocha for pure JS testing but failed and moved on.
* Fixing smaller bugs - maintain the alpha
* List ideas for future
* Suggesting collaboration platforms. I used Trello until now. 
* Anything else :)

Thanks @wsakka and lurkers, looking forward to your replies 🎉

**Comment by ajthinking** [comment]
I tried to compile all the bugs and feature requests into a [Trello board](https://trello.com/b/R11mhfdy/pipe-dream)

**Comment by ajthinking** [comment]
Thanks @wsakka ! This is queued in next version, closing for now.
