### ISSUE TITLE
Syntax error or access violation: 1067 Invalid default value for 'created_at

### ISSUE THREAD

**Issue by popescumarian** [pipe-dream/laravel#12]
Hi, I am getting this error: **"Syntax error or access violation: 1067 Invalid default value for 'created_at"** when I migrate the generated migrations. 
If I replace the generated timestamp('created_at') and timestamp('updated_at') with timestamps() then this error is gone.
I am using Laravel 5.8.

**Comment by calvinchiulele** [comment]
This is because the $table->timestamps('created_at') statement doesn't include a default value for the timestamps column. We should make a PR to fix that bug. To fix this, we have to write the follow in the migration file:
$table->timestamp('created_at')->nullable();
$table->timestamp('updated_at')->nullable();

You can use $table->timestamps() instead.

**Comment by ajthinking** [comment]
Thanks for reporting @popescumarian ! That one slid right through when using sqlite.  Im looking into it now.

**Comment by ajthinking** [comment]
Added to this [Trello board](https://trello.com/b/R11mhfdy/pipe-dream). Did not make it today, coming back tomorrow. Thanks @calvinchiulele for pointing out the reason!

**Comment by sinaghazi** [comment]
as a quick fix on this, on line 85 of AttributeFactory.js you can change the getNullable method to: 

`getNullable() {
        if (this.getForeign() || ['created_at', 'updated_at'].includes(this.name)){
            return true;
        }else{
            return false;
        }
    }`

**Comment by ajthinking** [comment]
Fix for the default timestamps released in `v0.0.44`. Further updates to come later. Thanks yall!
