### ISSUE TITLE
Add user system button should scaffold template files

### ISSUE THREAD

**Issue by SamuelNitsche** [pipe-dream/laravel#36]
First of all I want to tell you that this is an amazing idea!

I think that the "+ user system" button should also scaffold all views and styles, like "php artisan make:auth" does. Maybe also making it optional would be nice. What do you think about this?

**Comment by ajthinking** [comment]
Thanks @SamuelNitsche !
Nice suggestion, that would be helpful indeed! Not 100% sure how to implement that in a flexible manner since people are using very different frontends (not as predictable as the backend). It might require not just a new Pipe but a new VueFileFactory/ReactFileFactory or similar to handle frontend.  I will list it in the TODO board for now.
