### ISSUE TITLE
Have you checked Infyom?

### ISSUE THREAD

**Issue by JafarAkhondali** [pipe-dream/laravel#9]
Hello, Thanks for creating this repository.
But there is a similar project which is older and got tons of features called [Infyom](https://github.com/InfyOmLabs). Did you see their work? Is this project gonna offer something that they don't?

**Comment by ajthinking** [comment]
Hi, thanks for the tip!
Yes I did and while its powerful I still saw lots of room for improvement. For instance
* easier installation
* help with schema creation
* giving the user predictions
* modifying the templates
* having a GUI instead of CLI
* real time review
...

probably some more points that I forgot.
